// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubcajxdpjmszcmymwoze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InViY2FqeGRwam1zemNteW13b3plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NzcyODQsImV4cCI6MjA2OTI1MzI4NH0.V4V5698oV4_1NJE3qPSxAYyizbKa37Q5lBDEqHi7ihA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});